#!/bin/bash
set -euo pipefail
exec > /var/log/user-data.log 2>&1

echo "=== [1/6] Installing Docker ==="
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-plugin awscli jq git
systemctl enable docker
systemctl start docker
usermod -aG docker ubuntu

echo "=== [2/6] Fetching secrets from AWS Secrets Manager ==="
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "${secret_arn}" \
  --region "${aws_region}" \
  --query SecretString --output text)

SECRET_KEY=$(echo "$SECRET_JSON" | jq -r '.SECRET_KEY')
POSTGRES_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.POSTGRES_PASSWORD')
REDIS_AUTH_TOKEN=$(echo "$SECRET_JSON" | jq -r '.REDIS_AUTH_TOKEN')
N8N_PASSWORD=$(echo "$SECRET_JSON" | jq -r '.N8N_PASSWORD')
N8N_CALLBACK_SECRET=$(echo "$SECRET_JSON" | jq -r '.N8N_CALLBACK_SECRET')
CREDENTIAL_ENCRYPTION_KEY=$(echo "$SECRET_JSON" | jq -r '.CREDENTIAL_ENCRYPTION_KEY')

PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || echo "localhost")

echo "=== [3/6] Cloning repository ==="
cd /home/ubuntu
if [ ! -d "llm-platform" ]; then
  # If repo isn't synced via rsync, create placeholder
  mkdir -p llm-platform
fi
cd llm-platform

echo "=== [4/6] Writing .env ==="
cat > .env << ENVEOF
# Auto-generated by Terraform — secrets from AWS Secrets Manager
# ${project_name} / ${environment}

DEBUG=true
SECRET_KEY=$SECRET_KEY
CREDENTIAL_ENCRYPTION_KEY=$CREDENTIAL_ENCRYPTION_KEY

# Database — AWS RDS PostgreSQL
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql+asyncpg://${db_name}:$POSTGRES_PASSWORD@${db_host}:${db_port}/${db_name}
DATABASE_URL_SYNC=postgresql://${db_name}:$POSTGRES_PASSWORD@${db_host}:${db_port}/${db_name}

# Redis — AWS ElastiCache (TLS)
REDIS_URL=rediss://:$REDIS_AUTH_TOKEN@${redis_host}:${redis_port}/0

# n8n
N8N_USER=admin
N8N_PASSWORD=$N8N_PASSWORD
N8N_CALLBACK_SECRET=$N8N_CALLBACK_SECRET

# CORS
CORS_ORIGINS=http://$PUBLIC_IP:3000

# Optional — fill in manually if needed
AGENT_LLM_API_KEY=
AGENT_LLM_PROVIDER=openai
AGENT_LLM_MODEL=gpt-4o-mini
HF_TOKEN=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRO_PRICE_ID=
STRIPE_ENTERPRISE_PRICE_ID=
ENVEOF

chmod 600 .env
chown ubuntu:ubuntu .env

echo "=== [5/6] Writing docker-compose.staging-aws.yml ==="
cat > docker-compose.staging-aws.yml << 'COMPOSEEOF'
# Staging on AWS — uses RDS PostgreSQL + ElastiCache Redis
# No local postgres/redis containers needed

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: $${DATABASE_URL}
      DATABASE_URL_SYNC: $${DATABASE_URL_SYNC}
      REDIS_URL: $${REDIS_URL}
      SECRET_KEY: $${SECRET_KEY}
      CREDENTIAL_ENCRYPTION_KEY: $${CREDENTIAL_ENCRYPTION_KEY}
      N8N_CALLBACK_SECRET: $${N8N_CALLBACK_SECRET}
      CORS_ORIGINS: $${CORS_ORIGINS}
      DEBUG: $${DEBUG:-true}
      HF_TOKEN: $${HF_TOKEN:-}
      STRIPE_SECRET_KEY: $${STRIPE_SECRET_KEY:-}
      STRIPE_WEBHOOK_SECRET: $${STRIPE_WEBHOOK_SECRET:-}
      STRIPE_PRO_PRICE_ID: $${STRIPE_PRO_PRICE_ID:-}
      STRIPE_ENTERPRISE_PRICE_ID: $${STRIPE_ENTERPRISE_PRICE_ID:-}
      AGENT_LLM_API_KEY: $${AGENT_LLM_API_KEY:-}
      AGENT_LLM_PROVIDER: $${AGENT_LLM_PROVIDER:-openai}
      AGENT_LLM_MODEL: $${AGENT_LLM_MODEL:-gpt-4o-mini}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://backend:8000
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=$${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=$${N8N_PASSWORD}
      - WEBHOOK_URL=http://backend:8000
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  n8n_data:
COMPOSEEOF

chown ubuntu:ubuntu docker-compose.staging-aws.yml

echo "=== [6/6] Ready ==="
echo "VM is ready. To deploy:"
echo "  1. rsync your code to /home/ubuntu/llm-platform/"
echo "  2. cd /home/ubuntu/llm-platform"
echo "  3. docker compose -f docker-compose.staging-aws.yml up -d --build"
echo ""
echo "Frontend: http://$PUBLIC_IP:3000"
echo "Backend:  http://$PUBLIC_IP:8000/docs"
echo "n8n:      http://$PUBLIC_IP:5678"
