"""
Config Bundler — packages deployment configs into a downloadable ZIP.
"""

import io
import zipfile


def create_deploy_bundle(
    configs: dict,
    model_name: str,
    cloud_provider: str,
) -> bytes:
    """Create a ZIP archive containing all deployment configuration files."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("Dockerfile", configs.get("dockerfile", ""))
        zf.writestr("kubernetes.yaml", configs.get("kubernetes_yaml", ""))

        # Terraform in its own folder
        tf = configs.get("terraform_config", "")
        zf.writestr(f"terraform/main.tf", tf)

        # CI/CD
        zf.writestr(
            ".github/workflows/deploy.yml",
            configs.get("ci_cd_pipeline", ""),
        )

        # CloudFormation (AWS only)
        cf = configs.get("cloudformation", "")
        if cf:
            zf.writestr("cloudformation.yaml", cf)

        # Merge config (if model merging)
        mc = configs.get("merge_config", "")
        if mc:
            zf.writestr("merge_config.yaml", mc)

        # Quickstart script
        qs = configs.get("quickstart", "")
        if qs:
            zf.writestr("quickstart.sh", qs)

        # README
        zf.writestr("README.md", _generate_readme(model_name, cloud_provider, configs))

    return buf.getvalue()


def _generate_readme(model_name: str, cloud_provider: str, configs: dict) -> str:
    has_merge = bool(configs.get("merge_config"))
    has_lora = "enable-lora" in configs.get("dockerfile", "")

    lines = [
        f"# {model_name} — Deployment Bundle",
        "",
        f"Cloud: **{cloud_provider.upper()}**",
        "",
        "## Contents",
        "",
        "| File | Description |",
        "| --- | --- |",
        "| `Dockerfile` | vLLM inference server container |",
        "| `kubernetes.yaml` | K8s Deployment, Service, HPA |",
        "| `terraform/main.tf` | Cloud infrastructure (VPC, cluster, registry) |",
        "| `.github/workflows/deploy.yml` | CI/CD pipeline |",
    ]
    if configs.get("cloudformation"):
        lines.append("| `cloudformation.yaml` | AWS CloudFormation stack |")
    if has_merge:
        lines.append("| `merge_config.yaml` | mergekit merge recipe |")
    lines.append("| `quickstart.sh` | Step-by-step deploy commands |")

    lines.extend([
        "",
        "## Quick Start",
        "",
        "```bash",
        "chmod +x quickstart.sh",
        "# Follow the steps in quickstart.sh",
        "```",
    ])

    if has_merge:
        lines.extend([
            "",
            "## Model Merging",
            "",
            "This config uses **mergekit** to merge models at Docker build time.",
            "The `merge_config.yaml` defines the merge recipe.",
        ])

    if has_lora:
        lines.extend([
            "",
            "## LoRA Adapter",
            "",
            "The Dockerfile enables LoRA at runtime via vLLM's `--enable-lora` flag.",
            "The adapter is loaded from HuggingFace automatically.",
        ])

    lines.extend([
        "",
        "---",
        "Generated by LLM Cloud Platform",
    ])

    return "\n".join(lines) + "\n"
